# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/PyCQA/autoflake
      rev: "v1.4"
      hooks:
          - id: autoflake
            entry: autoflake --in-place --remove-all-unused-imports --remove-unused-variables
            language: python
            "types": [python]
            require_serial: true
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            entry: black
