PLAYER_SPEED = 8
BLOCKS_RENDER_DISTANCE = 20
WORLD_SIZE = 500
ENEMIES_TOTAL = 100
ISLAND_SEED_CLASSIC = 34315

LOGGER_NAME = "game"
LOGGER_FILE_NAME = "log"
LOGGER_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
