PLAYER_SPEED = 5
BLOCKS_RENDER_DISTANCE = 16
WORLD_SIZE = 500
ISLAND_SEED_CLASSIC = 34315  # 48893

LOGGER_NAME = "game"
LOGGER_FILE_NAME = "log"
LOGGER_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
